name: Deploy Terraform

on:
  workflow_dispatch
 # push:
  #  branches:
   #   - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Specify the desired Terraform version
    
    # Step 3: Terraform Init
    - name: Terraform Init
      run: terraform init

    # Étape 4 : Configurer les identifiants AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"

    # Step 5: Terraform Plan
    - name: Terraform Plan
      run: terraform plan
      #env:
        #TF_VAR_environment: dev # Example variable, adjust as necessary

    # Step 6: Terraform Apply
    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' # Conditional execution
      run: terraform apply -auto-approve
      #env:
       # TF_VAR_environment: dev # Example variable, adjust as necessary
